export const usersActionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

    GET_CURRENT_USER_REQUEST: "GET_CURRENT_USER_REQUEST",
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_FAILURE: "GET_CURRENT_USER_FAILURE"
}